name: Release Documentation

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  release:
    types: [created, published]

jobs:
  build_html:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setupt Pixi
        uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
        with:
          pixi-version: 'latest'
          locked: true
          cache: true
          cache-write: ${{ github.ref == 'refs/heads/main' }}
          environments: doc

      - name: Build HTML
        run: |
          pixi reinstall -e doc geoPFA
          pixi run -e doc python-docs  # This errors on warnings

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'docs/build/html'

  deploy:
    name: Deploy docs
    needs: build_html
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
