name: Lint source code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - uses: ./.github/actions/configure-latticekrigx
      with:
        deploy-key: ${{ secrets.LATTICEKRIGX_DEPLOY_KEY }}

    - name: Set up Python
      uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
      with:
        pixi-version: 'latest'
        # locked: true
        frozen: true
        cache: true

    - name: Analysing the code with pylint
      run: pixi run -e test pylint $(git ls-files '*.py')
