name: Lint source code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: prefix-dev/setup-pixi@d3f436a425481402e6a95a1d1fc10331c708cd9e # v0.10.2
      with:
        pixi-version: 'latest'
        # locked: true
        frozen: true
        cache: true

    - name: Analysing the code with pylint
      run: pixi run -e test pylint $(git ls-files '*.py')
